keys:
  - &host_calvin age1cf896thek5up8ghqqgxw9twz4ssrf8z200a350uhjafmp7s4kdjsrncxk6
  - &host_frankenbook age1xp5hezyj8l8heum9gzmdve9hnuv2l7vxy3xa6gnze28zqk2pwpkswn5l9u
  - &host_mowteng age1m2g0h0m5ctv0pvcrlv9rz3jdhhsqg97q3krxjfp29rc7x4sv95pscn84qt
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *host_calvin
        - *host_frankenbook
        - *host_mowteng
