# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];


  boot.loader = {
    systemd-boot.enable = true;
    efi.canTouchEfiVariables = true;
    efi.efiSysMountPoint = "/efi";
  };

  boot = {
    initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "uas" "usb_storage" "sd_mod" ];
    initrd.kernelModules = [ "amd_pstate" "amdgpu" ];
    kernelModules = [ "hid-nintendo" "kvm-amd" ];
    kernelPackages =
      #pkgs.linuxPackages_xanmod_latest
      pkgs.linuxPackages_zen
    ;
    kernelParams = [
      "amd_pstate.shared_mem=1"
    ];
  };



  fileSystems."/" = {
    #device = "/dev/disk/by-uuid/cd229a4c-f1ba-435e-99a4-208504e3fe63";
    device = "/dev/disk/by-uuid/00af92b2-0a8a-47b0-8e61-aac1789b25e5";
    fsType = "btrfs";
    options = [
      "subvol=@root"
      "compress=zstd:9"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/00af92b2-0a8a-47b0-8e61-aac1789b25e5";
    fsType = "btrfs";
    options = [
      "subvol=@nix"
      "compress=zstd:9"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/cd229a4c-f1ba-435e-99a4-208504e3fe63";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "compress=zstd:9"
    ];
  };

  fileSystems."/efi" = {
    device = "/dev/disk/by-uuid/FC8E-197A";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
      "codepage=437"
      "iocharset=ascii"
      "shortname=mixed"
      "utf8"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/f747ba5c-e68a-4862-8df0-2f5ffe72a82f"; }
  ];


  hardware = {
    cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    enableRedistributableFirmware = true;
    bluetooth.enable = true;

    opengl.extraPackages = with pkgs; [
      rocm-opencl-icd
      rocm-opencl-runtime
      amdvlk
    ];
    opengl.extraPackages32 = with pkgs; [
      driversi686Linux.amdvlk
    ];

    opengl = {
      driSupport = lib.mkDefault true;
      driSupport32Bit = lib.mkDefault true;
    };

    sensor.iio.enable = true;
    uinput.enable = true;
    xpadneo.enable = true;

  };

  services.logind.lidSwitch = "hibernate";
  #systemd.sleep.extraConfig = ''
  #  HibernateMode=shutdown
  #'';

  environment.variables.AMD_VULKAN_ICD = lib.mkDefault "RADV";

  environment.systemPackages = with pkgs; [
    lm_sensors
  ];

  powerManagement = {
    cpuFreqGovernor = "schedutil";
    powertop.enable = false;
  };

  sound.enable = true;

  location = {
    latitude = 50.9787;
    longitude = 11.03283;
  };
}
