# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];


  boot.loader = {
    systemd-boot.enable = true;
    efi.canTouchEfiVariables = true;
    efi.efiSysMountPoint = "/efi";
  };

  boot = {
    initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "sd_mod" ];
    initrd.kernelModules = [ "amd_pstate" "amdgpu" ];
    kernelModules = [ "kvm-amd" "zenpower" ];
    extraModulePackages = [ pkgs.linuxPackages_lqx.zenpower ];
    kernelPackages = pkgs.linuxPackages_lqx;
    kernelPatches = [
      {
        name = "d3cold-fix";
        patch = ./patches/d3cold.patch;
      }
    ];
    kernelParams = [
      "amd_pstate.shared_mem=1"
    ];
  };



  fileSystems."/" = {
    device = "/dev/disk/by-uuid/d1f0114c-069e-46c1-bf58-f2d024ca46f7";
    fsType = "btrfs";
    options = [
      "subvol=@nixroot"
      "compress=zstd:9"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/d1f0114c-069e-46c1-bf58-f2d024ca46f7";
    fsType = "btrfs";
    options = [
      "subvol=@nix"
      "compress=zstd:9"
    ];
  };

  fileSystems."/efi" = {
    device = "/dev/disk/by-uuid/7141-64D6";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
      "codepage=437"
      "iocharset=ascii"
      "shortname=mixed"
      "utf8"
    ];
  };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/d1f0114c-069e-46c1-bf58-f2d024ca46f7";
      fsType = "btrfs";
      options = [ 
        "subvol=@home"
        "compress=zstd:9"
      ];
    };

  fileSystems."/data/Games" =
    { device = "/dev/disk/by-uuid/d1f0114c-069e-46c1-bf58-f2d024ca46f7";
      fsType = "btrfs";
      options = [ 
        "subvol=@GameData"
        "compress=zstd:9"
      ];
    };

  fileSystems."/data/butter" =
    { device = "/dev/disk/by-uuid/d1f0114c-069e-46c1-bf58-f2d024ca46f7";
      fsType = "btrfs";
    };

  fileSystems."/data/snapshots" =
    { device = "/dev/disk/by-uuid/d1f0114c-069e-46c1-bf58-f2d024ca46f7";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/cbd786fb-2d29-4652-9749-ab5e2b4fbee9"; }
  ];

  hardware = {
    cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    enableRedistributableFirmware = true;
    bluetooth.enable = true;

    opengl = {
      driSupport = lib.mkDefault true;
      driSupport32Bit = lib.mkDefault true;
    };

    sensor.iio.enable = true;
    uinput.enable = true;
    xpadneo.enable = true;

  };

  services.logind.lidSwitch = "suspend";
  #systemd.sleep.extraConfig = ''
  #  HibernateMode=shutdown
  #'';

  environment.variables.AMD_VULKAN_ICD = lib.mkDefault "RADV";

  environment.systemPackages = with pkgs; [
    lm_sensors
    linuxKernel.packages.linux_lqx.cpupower
  ];

  powerManagement = {
    cpuFreqGovernor = "schedutil";
    powertop.enable = false;
  };

  sound.enable = true;

  location = {
    latitude = 50.9787;
    longitude = 11.03283;
  };
}
